name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: "actions/checkout@v2"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v2-beta"
        with:
          node-version: "14"

      - uses: actions/cache@v2
        id: cache-node
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Update npm
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm i -g npm

      - name: Install deps
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm ci

  lint:
    needs: setup

    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"

      - name: Use cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Update npm
        run: npm i -g npm

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

  build:
    needs: setup

    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"

      - name: Use cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Update npm
        run: npm i -g npm

      - name: Install deps
        run: npm ci

      - name: "Type check"
        run: "npm run typecheck"

      - name: "Build"
        run: "npm run build"
